const currencyList = [
  // A
  { code: "AFN", symbol: "؋", name: "Afghan Afghani", country: "Afghanistan" },
  { code: "ALL", symbol: "L", name: "Albanian Lek", country: "Albania" },
  { code: "DZD", symbol: "د.ج", name: "Algerian Dinar", country: "Algeria" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "American Samoa" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Andorra" },
  { code: "AOA", symbol: "Kz", name: "Angolan Kwanza", country: "Angola" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar", country: "Antigua and Barbuda" },
  { code: "ARS", symbol: "$", name: "Argentine Peso", country: "Argentina" },
  { code: "AMD", symbol: "֏", name: "Armenian Dram", country: "Armenia" },
  { code: "AWG", symbol: "ƒ", name: "Aruban Florin", country: "Aruba" },
  { code: "AUD", symbol: "$", name: "Australian Dollar", country: "Australia" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Austria" },
  { code: "AZN", symbol: "₼", name: "Azerbaijani Manat", country: "Azerbaijan" },

  // B
  { code: "BSD", symbol: "$", name: "Bahamian Dollar", country: "Bahamas" },
  { code: "BHD", symbol: ".د.ب", name: "Bahraini Dinar", country: "Bahrain" },
  { code: "BDT", symbol: "৳", name: "Bangladeshi Taka", country: "Bangladesh" },
  { code: "BBD", symbol: "$", name: "Barbadian Dollar", country: "Barbados" },
  { code: "BYN", symbol: "Br", name: "Belarusian Ruble", country: "Belarus" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Belgium" },
  { code: "BZD", symbol: "$", name: "Belize Dollar", country: "Belize" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "Benin" },
  { code: "BMD", symbol: "$", name: "Bermudian Dollar", country: "Bermuda" },
  { code: "BTN", symbol: "Nu.", name: "Bhutanese Ngultrum", country: "Bhutan" },
  { code: "BOB", symbol: "Bs.", name: "Bolivian Boliviano", country: "Bolivia" },
  { code: "BAM", symbol: "КМ", name: "Bosnia and Herzegovina Convertible Mark", country: "Bosnia and Herzegovina" },
  { code: "BWP", symbol: "P", name: "Botswanan Pula", country: "Botswana" },
  { code: "BRL", symbol: "R$", name: "Brazilian Real", country: "Brazil" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "British Virgin Islands" },
  { code: "BND", symbol: "$", name: "Brunei Dollar", country: "Brunei" },
  { code: "BGN", symbol: "лв", name: "Bulgarian Lev", country: "Bulgaria" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "Burkina Faso" },
  { code: "BIF", symbol: "Fr", name: "Burundian Franc", country: "Burundi" },

  // C
  { code: "KHR", symbol: "៛", name: "Cambodian Riel", country: "Cambodia" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", country: "Cameroon" },
  { code: "CAD", symbol: "$", name: "Canadian Dollar", country: "Canada" },
  { code: "CVE", symbol: "$", name: "Cape Verdean Escudo", country: "Cape Verde" },
  { code: "KYD", symbol: "$", name: "Cayman Islands Dollar", country: "Cayman Islands" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", country: "Central African Republic" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", country: "Chad" },
  { code: "CLP", symbol: "$", name: "Chilean Peso", country: "Chile" },
  { code: "CNY", symbol: "¥", name: "Chinese Yuan", country: "China" },
  { code: "COP", symbol: "$", name: "Colombian Peso", country: "Colombia" },
  { code: "KMF", symbol: "Fr", name: "Comorian Franc", country: "Comoros" },
  { code: "CDF", symbol: "Fr", name: "Congolese Franc", country: "Democratic Republic of the Congo" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", country: "Republic of the Congo" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar", country: "Cook Islands" },
  { code: "CRC", symbol: "₡", name: "Costa Rican Colón", country: "Costa Rica" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "Côte d'Ivoire" },
  { code: "HRK", symbol: "kn", name: "Croatian Kuna", country: "Croatia" },
  { code: "CUP", symbol: "$", name: "Cuban Peso", country: "Cuba" },
  { code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder", country: "Curaçao" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Cyprus" },
  { code: "CZK", symbol: "Kč", name: "Czech Koruna", country: "Czech Republic" },

  // D
  { code: "DKK", symbol: "kr", name: "Danish Krone", country: "Denmark" },
  { code: "DJF", symbol: "Fr", name: "Djiboutian Franc", country: "Djibouti" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar", country: "Dominica" },
  { code: "DOP", symbol: "$", name: "Dominican Peso", country: "Dominican Republic" },

  // E
  { code: "USD", symbol: "$", name: "US Dollar", country: "East Timor" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Ecuador" },
  { code: "EGP", symbol: "£", name: "Egyptian Pound", country: "Egypt" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "El Salvador" },
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", country: "Equatorial Guinea" },
  { code: "ERN", symbol: "Nfk", name: "Eritrean Nakfa", country: "Eritrea" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Estonia" },
  { code: "SZL", symbol: "L", name: "Swazi Lilangeni", country: "Eswatini" },
  { code: "ETB", symbol: "Br", name: "Ethiopian Birr", country: "Ethiopia" },

  // F
  { code: "FKP", symbol: "£", name: "Falkland Islands Pound", country: "Falkland Islands" },
  { code: "DKK", symbol: "kr", name: "Danish Krone", country: "Faroe Islands" },
  { code: "FJD", symbol: "$", name: "Fijian Dollar", country: "Fiji" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Finland" },
  { code: "EUR", symbol: "€", name: "Euro", country: "France" },
  { code: "EUR", symbol: "€", name: "Euro", country: "French Guiana" },
  { code: "XPF", symbol: "₣", name: "CFP Franc", country: "French Polynesia" },

  // G
  { code: "XAF", symbol: "FCFA", name: "Central African CFA Franc", country: "Gabon" },
  { code: "GMD", symbol: "D", name: "Gambian Dalasi", country: "Gambia" },
  { code: "GEL", symbol: "₾", name: "Georgian Lari", country: "Georgia" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Germany" },
  { code: "GHS", symbol: "₵", name: "Ghanaian Cedi", country: "Ghana" },
  { code: "GIP", symbol: "£", name: "Gibraltar Pound", country: "Gibraltar" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Greece" },
  { code: "DKK", symbol: "kr", name: "Danish Krone", country: "Greenland" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar", country: "Grenada" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Guadeloupe" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Guam" },
  { code: "GTQ", symbol: "Q", name: "Guatemalan Quetzal", country: "Guatemala" },
  { code: "GBP", symbol: "£", name: "British Pound", country: "Guernsey" },
  { code: "GNF", symbol: "Fr", name: "Guinean Franc", country: "Guinea" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "Guinea-Bissau" },
  { code: "GYD", symbol: "$", name: "Guyanese Dollar", country: "Guyana" },

  // H
  { code: "HTG", symbol: "G", name: "Haitian Gourde", country: "Haiti" },
  { code: "HNL", symbol: "L", name: "Honduran Lempira", country: "Honduras" },
  { code: "HKD", symbol: "$", name: "Hong Kong Dollar", country: "Hong Kong" },
  { code: "HUF", symbol: "Ft", name: "Hungarian Forint", country: "Hungary" },

  // I
  { code: "ISK", symbol: "kr", name: "Icelandic Króna", country: "Iceland" },
  { code: "INR", symbol: "₹", name: "Indian Rupee", country: "India" },
  { code: "IDR", symbol: "Rp", name: "Indonesian Rupiah", country: "Indonesia" },
  { code: "IRR", symbol: "﷼", name: "Iranian Rial", country: "Iran" },
  { code: "IQD", symbol: "ع.د", name: "Iraqi Dinar", country: "Iraq" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Ireland" },
  { code: "GBP", symbol: "£", name: "British Pound", country: "Isle of Man" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel", country: "Israel" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Italy" },

  // J
  { code: "JMD", symbol: "$", name: "Jamaican Dollar", country: "Jamaica" },
  { code: "JPY", symbol: "¥", name: "Japanese Yen", country: "Japan" },
  { code: "GBP", symbol: "£", name: "British Pound", country: "Jersey" },
  { code: "JOD", symbol: "د.ا", name: "Jordanian Dinar", country: "Jordan" },

  // K
  { code: "KZT", symbol: "₸", name: "Kazakhstani Tenge", country: "Kazakhstan" },
  { code: "KES", symbol: "Sh", name: "Kenyan Shilling", country: "Kenya" },
  { code: "AUD", symbol: "$", name: "Australian Dollar", country: "Kiribati" },
  { code: "KPW", symbol: "₩", name: "North Korean Won", country: "North Korea" },
  { code: "KRW", symbol: "₩", name: "South Korean Won", country: "South Korea" },
  { code: "KWD", symbol: "د.ك", name: "Kuwaiti Dinar", country: "Kuwait" },
  { code: "KGS", symbol: "с", name: "Kyrgyzstani Som", country: "Kyrgyzstan" },

  // L
  { code: "LAK", symbol: "₭", name: "Lao Kip", country: "Laos" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Latvia" },
  { code: "LBP", symbol: "ل.ل", name: "Lebanese Pound", country: "Lebanon" },
  { code: "LSL", symbol: "L", name: "Lesotho Loti", country: "Lesotho" },
  { code: "LRD", symbol: "$", name: "Liberian Dollar", country: "Liberia" },
  { code: "LYD", symbol: "ل.د", name: "Libyan Dinar", country: "Libya" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc", country: "Liechtenstein" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Lithuania" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Luxembourg" },

  // M
  { code: "MOP", symbol: "P", name: "Macanese Pataca", country: "Macau" },
  { code: "MKD", symbol: "ден", name: "Macedonian Denar", country: "North Macedonia" },
  { code: "MGA", symbol: "Ar", name: "Malagasy Ariary", country: "Madagascar" },
  { code: "MWK", symbol: "MK", name: "Malawian Kwacha", country: "Malawi" },
  { code: "MYR", symbol: "RM", name: "Malaysian Ringgit", country: "Malaysia" },
  { code: "MVR", symbol: ".ރ", name: "Maldivian Rufiyaa", country: "Maldives" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "Mali" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Malta" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Marshall Islands" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Martinique" },
  { code: "MRU", symbol: "UM", name: "Mauritanian Ouguiya", country: "Mauritania" },
  { code: "MUR", symbol: "₨", name: "Mauritian Rupee", country: "Mauritius" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Mayotte" },
  { code: "MXN", symbol: "$", name: "Mexican Peso", country: "Mexico" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Micronesia" },
  { code: "MDL", symbol: "L", name: "Moldovan Leu", country: "Moldova" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Monaco" },
  { code: "MNT", symbol: "₮", name: "Mongolian Tögrög", country: "Mongolia" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Montenegro" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar", country: "Montserrat" },
  { code: "MAD", symbol: "د.م.", name: "Moroccan Dirham", country: "Morocco" },
  { code: "MZN", symbol: "MT", name: "Mozambican Metical", country: "Mozambique" },
  { code: "MMK", symbol: "Ks", name: "Myanmar Kyat", country: "Myanmar" },

  // N
  { code: "NAD", symbol: "$", name: "Namibian Dollar", country: "Namibia" },
  { code: "AUD", symbol: "$", name: "Australian Dollar", country: "Nauru" },
  { code: "NPR", symbol: "₨", name: "Nepalese Rupee", country: "Nepal" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Netherlands" },
  { code: "XPF", symbol: "₣", name: "CFP Franc", country: "New Caledonia" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar", country: "New Zealand" },
  { code: "NIO", symbol: "C$", name: "Nicaraguan Córdoba", country: "Nicaragua" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "Niger" },
  { code: "NGN", symbol: "₦", name: "Nigerian Naira", country: "Nigeria" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar", country: "Niue" },
  { code: "AUD", symbol: "$", name: "Australian Dollar", country: "Norfolk Island" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Northern Mariana Islands" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone", country: "Norway" },

  // O
  { code: "OMR", symbol: "ر.ع.", name: "Omani Rial", country: "Oman" },

  // P
  { code: "PKR", symbol: "₨", name: "Pakistani Rupee", country: "Pakistan" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Palau" },
  { code: "ILS", symbol: "₪", name: "Israeli New Shekel", country: "Palestine" },
  { code: "PAB", symbol: "B/.", name: "Panamanian Balboa", country: "Panama" },
  { code: "PGK", symbol: "K", name: "Papua New Guinean Kina", country: "Papua New Guinea" },
  { code: "PYG", symbol: "₲", name: "Paraguayan Guaraní", country: "Paraguay" },
  { code: "PEN", symbol: "S/", name: "Peruvian Sol", country: "Peru" },
  { code: "PHP", symbol: "₱", name: "Philippine Peso", country: "Philippines" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar", country: "Pitcairn Islands" },
  { code: "PLN", symbol: "zł", name: "Polish Złoty", country: "Poland" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Portugal" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Puerto Rico" },

  // Q
  { code: "QAR", symbol: "ر.ق", name: "Qatari Riyal", country: "Qatar" },

  // R
  { code: "EUR", symbol: "€", name: "Euro", country: "Réunion" },
  { code: "RON", symbol: "lei", name: "Romanian Leu", country: "Romania" },
  { code: "RUB", symbol: "₽", name: "Russian Ruble", country: "Russia" },
  { code: "RWF", symbol: "Fr", name: "Rwandan Franc", country: "Rwanda" },

  // S
  { code: "EUR", symbol: "€", name: "Euro", country: "Saint Barthélemy" },
  { code: "SHP", symbol: "£", name: "Saint Helena Pound", country: "Saint Helena" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar", country: "Saint Kitts and Nevis" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar", country: "Saint Lucia" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Saint Martin" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Saint Pierre and Miquelon" },
  { code: "XCD", symbol: "$", name: "East Caribbean Dollar", country: "Saint Vincent and the Grenadines" },
  { code: "WST", symbol: "T", name: "Samoan Tālā", country: "Samoa" },
  { code: "EUR", symbol: "€", name: "Euro", country: "San Marino" },
  { code: "STN", symbol: "Db", name: "São Tomé and Príncipe Dobra", country: "São Tomé and Príncipe" },
  { code: "SAR", symbol: "ر.س", name: "Saudi Riyal", country: "Saudi Arabia" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "Senegal" },
  { code: "RSD", symbol: "дин.", name: "Serbian Dinar", country: "Serbia" },
  { code: "SCR", symbol: "₨", name: "Seychellois Rupee", country: "Seychelles" },
  { code: "SLE", symbol: "Le", name: "Sierra Leonean Leone", country: "Sierra Leone" },
  { code: "SGD", symbol: "$", name: "Singapore Dollar", country: "Singapore" },
  { code: "ANG", symbol: "ƒ", name: "Netherlands Antillean Guilder", country: "Sint Maarten" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Slovakia" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Slovenia" },
  { code: "SBD", symbol: "$", name: "Solomon Islands Dollar", country: "Solomon Islands" },
  { code: "SOS", symbol: "Sh", name: "Somali Shilling", country: "Somalia" },
  { code: "ZAR", symbol: "R", name: "South African Rand", country: "South Africa" },
  { code: "GBP", symbol: "£", name: "British Pound", country: "South Georgia and the South Sandwich Islands" },
  { code: "SSP", symbol: "£", name: "South Sudanese Pound", country: "South Sudan" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Spain" },
  { code: "LKR", symbol: "Rs", name: "Sri Lankan Rupee", country: "Sri Lanka" },
  { code: "SDG", symbol: "ج.س.", name: "Sudanese Pound", country: "Sudan" },
  { code: "SRD", symbol: "$", name: "Surinamese Dollar", country: "Suriname" },
  { code: "NOK", symbol: "kr", name: "Norwegian Krone", country: "Svalbard and Jan Mayen" },
  { code: "SEK", symbol: "kr", name: "Swedish Krona", country: "Sweden" },
  { code: "CHF", symbol: "Fr", name: "Swiss Franc", country: "Switzerland" },
  { code: "SYP", symbol: "£", name: "Syrian Pound", country: "Syria" },

  // T
  { code: "TWD", symbol: "$", name: "New Taiwan Dollar", country: "Taiwan" },
  { code: "TJS", symbol: "ЅМ", name: "Tajikistani Somoni", country: "Tajikistan" },
  { code: "TZS", symbol: "Sh", name: "Tanzanian Shilling", country: "Tanzania" },
  { code: "THB", symbol: "฿", name: "Thai Baht", country: "Thailand" },
  { code: "XOF", symbol: "CFA", name: "West African CFA Franc", country: "Togo" },
  { code: "NZD", symbol: "$", name: "New Zealand Dollar", country: "Tokelau" },
  { code: "TOP", symbol: "T$", name: "Tongan Paʻanga", country: "Tonga" },
  { code: "TTD", symbol: "$", name: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago" },
  { code: "TND", symbol: "د.ت", name: "Tunisian Dinar", country: "Tunisia" },
  { code: "TRY", symbol: "₺", name: "Turkish Lira", country: "Turkey" },
  { code: "TMT", symbol: "m", name: "Turkmenistani Manat", country: "Turkmenistan" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Turks and Caicos Islands" },
  { code: "AUD", symbol: "$", name: "Australian Dollar", country: "Tuvalu" },

  // U
  { code: "UGX", symbol: "Sh", name: "Ugandan Shilling", country: "Uganda" },
  { code: "UAH", symbol: "₴", name: "Ukrainian Hryvnia", country: "Ukraine" },
  { code: "AED", symbol: "د.إ", name: "UAE Dirham", country: "United Arab Emirates" },
  { code: "GBP", symbol: "£", name: "British Pound", country: "United Kingdom" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "United States" },
  { code: "UYU", symbol: "$", name: "Uruguayan Peso", country: "Uruguay" },
  { code: "UZS", symbol: "so'm", name: "Uzbekistani Som", country: "Uzbekistan" },

  // V
  { code: "VUV", symbol: "Vt", name: "Vanuatu Vatu", country: "Vanuatu" },
  { code: "EUR", symbol: "€", name: "Euro", country: "Vatican City" },
  { code: "VES", symbol: "Bs.S", name: "Venezuelan Bolívar Soberano", country: "Venezuela" },
  { code: "VND", symbol: "₫", name: "Vietnamese Đồng", country: "Vietnam" },
  { code: "USD", symbol: "$", name: "US Dollar", country: "Virgin Islands (US)" },

  // W
  { code: "XPF", symbol: "₣", name: "CFP Franc", country: "Wallis and Futuna" },
  { code: "MAD", symbol: "د.م.", name: "Moroccan Dirham", country: "Western Sahara" },

  // Y
  { code: "YER", symbol: "﷼", name: "Yemeni Rial", country: "Yemen" },

  // Z
  { code: "ZMW", symbol: "ZK", name: "Zambian Kwacha", country: "Zambia" },
  { code: "ZWL", symbol: "$", name: "Zimbabwean Dollar", country: "Zimbabwe" }
];

export default currencyList;
